### ISSUE TITLE
pinMode in constructors

### ISSUE THREAD

**Issue by sterretjeToo** [SvenRosvall/SignalControl#3]
Hello

I've been helping in a topic on the Arduino Forum: https://forum.arduino.cc/t/4-aspect-railway-signalling-in-nz/1173058/5

I've noticed that your code calls pinMode() in the constructor. This is an incorrect approach, the pinMode() is executed and after that the hardware is initialised and wipes out the pinMode() settings. The usual approach is to add a begin() method to the class and call that begin() method from setup.

In the above link I demonstrated how it, in my opinion, should be done for the lights. The inputs are a little more complicated for me, I did not dive too deep in it but they also should be modified.

**Comment by fletchjp** [comment]
I have been asked by Sven to have a look at his code. I have compared the action of the PinInput constructor outside and inside the setup() function. I have looked at what has happened using code for getPinMode from this link https://forum.arduino.cc/t/getpinmode/232960. The output I get is the same for each. I know that the Arduino IDE runs quite a lot of code before setup() is run. In this case it seems it does not overwrite the pinMode setting.

**Comment by sterretjeToo** [comment]
I guess I should have phrased it a bit better :wink: It's a bad habit to do so. The fact that it works is on AVR based boards is no guarantee that it will work on other boards.

There are numerous topics all over the web (not only on forum.arduino.cc) that advise against it and to my knowledge there is even a topic on forum.arduino.cc for a non-AVR board where setting the pin mode in the constructor does not give the desired effect; I unfortunately could not find it back.

Comment https://github.com/mathertel/OneButton/issues/51#issuecomment-574137047 in https://github.com/mathertel/OneButton/issues/51 describes why it works on AVR based boards; the init() / initVariant() functions that are called from main() don't touch the modes.

**Comment by fletchjp** [comment]
Thank you for your comments. I think this is something we should follow, particularly as we want to have code which will run on different hardware.

**Comment by SvenRosvall** [comment]
Thanks you both for reviving this thread and providing information. John pointed me to a platform where pinMode() before setup() doesn't work. I accept that.

Refactoring the library to do the pinMode() in setup() is tricky as there may potentially be many objects that need to be initalized in setup(). 

To make it easy for the user the dependent objects are linked so the user would only need to call begin() (or whatever name to be used) for the top level objects. The library would then traverse all dependent objects and initialize them too. 

This will happen but I can't promis when as I have other projects going on right now.

**Comment by SvenRosvall** [comment]
Fixed in release v2.0.0
